### ISSUE TITLE
Pet Experience Bar

### ISSUE THREAD

**Issue by Manaether** [mfoltz/Eclipse#4]
State of the art : 
We are using the familiar with prestige system without the leveling system. ( in fact using everything but leveling and classes )

Problem: 
When enabled in the configuration the familiar experience bar doesn't show up

Fix : 
Split the configuration for familiar/player experience bar and enable the familiar bar when familiar leveling is on ?

**Comment by mfoltz** [comment]
there is not a bar for familiar experience nor is their a configuration option for one. most likely won't be added, at least not anytime soon.
